#!/usr/bin/python
import sys
import os
import subprocess
import stat
preflight_dir = '/usr/local/munki/preflight.d'
for script in os.listdir(preflight_dir):
    st = os.stat(os.path.join(preflight_dir, script))
    mode = st.st_mode
    if not mode & stat.S_IWOTH:
        try:
            subprocess.check_call([os.path.join(preflight_dir, script),
                            sys.argv[1]],
                            stdin=None)
        except OSError:
            print "Something went wrong!"
        except CalledProcessError as e: 
            sys.exit( e.returncode )
    else:
        print script + " is not executable or has bad permissions"
